### ISSUE TITLE
ad a --help command

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/SM2KG#11]
All python packages have a --help that explains how to invoke and the options the package has

**Comment by vmdiwanji** [comment]
Have implemented and pushed under the commit 'Added confidence and improved the parameters'

**Comment by dgarijo** [comment]
@vmdiwanji please do not close the issue directly, as I don't know where this has been fixed and by which commit. 
Instead, in the message of your commit ad a "Fix #11" and GitHub will automatically close the issue when it is merger in the main branch. 

When you think your branch is ready for me to test the issues, do a pull request to the main branch specifying the issues that have been fixed. I will review and merge accordingly. Thanks!

**Comment by dgarijo** [comment]
(These issues that you have closed is fine to leave them closed)
