### ISSUE TITLE
Create appropriate readme file

### ISSUE THREAD

**Issue by dgarijo** [KnowledgeCaptureAndDiscovery/SM2KG#8]
Right now the readme file is non-existent in this branch.

In the CLI branch, the readme file is incomplete, as it does not have:

- Markdown to indicate which parts are executable instructions.
- Instructions for installing the requirements.txt
- Instructions about a config.json file for the credentials.

**Comment by vmdiwanji** [comment]
Have implemented and pushed under the commit 'Added confidence and improved the parameters'
